### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by EliasBcd** [oTree-org/HR#2] opened 2021-07-02 09:42 UTC
I am sorry this is not going to be a very precise issue, but I thought it was worth listing the issues I had when using HR in production with MTurk.

First, at least when there are several sessions simultaneously, there seems to be an issue with getting the subjects for payments. I currently have a `KeyError at /MTurkPayments/yh1vhrwh/` and it cannot found one key. One explanation I have is that HR actually assumes there is only one session in the experiment, but I don't understand the code well enough to check it.

Second, for some subjects participating in the experiment, it did give the right participant label in otree, as I have something different from the WorkerID.  It may be an otree thing though. 

Finally, one suggestion I would make: if it were possible to pass the MTurk assignment ID to oTree, it would be a nice safety net for the user. In case HR fails, it would be easier for the user to manually pay the turkers.

I am sorry if this is a bit messy. I would be happy to participate in the improvements, but I don't understand the structure of the project and were the tables are stored to investigate the issues properly.

**Comment by oTree-org** [comment] 2021-07-02 10:56
Hi, thanks for reporting these issues, 

Issue 1: Could you provide the full traceback of the KeyError?

Issue 2: can you describe more what you mean? the participant label was wrong? If you could show a screenshot or something that would help me understand.

**Comment by EliasBcd** [comment] 2021-07-05 10:52
Issue 2:

**Comment by oTree-org** [comment] 2021-07-05 20:55
Hi, thank you very much for the info, I will investigate this.

**Comment by oTree-org** [comment] 2021-07-05 22:02
Hi, I can't reproduce this issue. Could you send me the logs from around the time when this happened, from either oTree HR, or oTree (or both)? Also, what version of oTree are you using?

**Comment by oTree-org** [comment] 2021-07-05 22:04
(Specifically, to have the logs when the participants joined the experiment, since it seemed the problem started when they clicked their start link.)

**Comment by oTree-org** [comment] 2021-07-06 01:28
Also if you know what browser was being used (Chrome/Firefox/etc)

**Comment by EliasBcd** [comment] 2021-07-06 08:05
I imagine it is for the second issue. 
Unfortunately it was more than a week ago and I did not keep the log of what happened. It may be a participant problem indeed.

**Comment by oTree-org** [comment] 2021-07-10 03:05
Hi, I think both of these issues are now fixed. Please open if it reoccurs. By the way I have set up a hosted version of oTree HR here: https://otree-hr.herokuapp.com/

**Closed by oTree-org** 2021-07-10 03:05 UTC
